title: The Cowboy Collective
description: The Cowboy Collective is a free-range group of artists making creative commons cowboy themed art!
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
paginate: 5
plugins: [jekyll-paginate]
